### ISSUE TITLE
Improve plugins section

### ISSUE THREAD

**Issue by xiaket** [buildkite/pipeline-schema#10]
Hi buildkite,

According to the schema, `plugins` should be an array of objects. However, in practice, buildkite happily accepted a pipeline with the following syntax:

```
    plugins:
      - ssh://git@scm.example.com/bkpl/namespace.git
      - docker-compose:
          run: k6-pipeline
          command: ["run", "tests/creditCardMakePayment.js"]
          config:
            - ./loadtesting/k6/docker-compose.yml
```

Note that the first item in the plugins array is of type string, not object.

Can we update the schema to reflect what we have in prod? Thanks!
