### ISSUE TITLE
Global `agents` is not defined in schema

### ISSUE THREAD

**Issue by gencer** [buildkite/pipeline-schema#11]
I see that global `agents` can be specified like this:

```yaml
agents: # <-- This one.
  os: ubuntu
  queue: default

steps:
  - command: echo "1"
  ...
```

However, current schema dıoes not show `agents` like above as a valid and does not autocomplete on VSCode.

See: https://forum.buildkite.community/t/setting-default-agents-for-a-build/111/3
