### ISSUE TITLE
test/valid-pipelines: trigger.yml does not seem to be valid

### ISSUE THREAD

**Issue by rogpeppe** [buildkite/pipeline-schema#131]
As of commit 2fbbfc199bd66c0ff64303a2d9c7072ad24f3ce3

The `trigger.yml` test does not seem to be valid against the schema.

Specifically the last two steps in that test instance data:

```
  - trigger: "a-slug"
    soft_fail:
      - exit_status: 1

  - trigger: "a-slug"
    soft_fail:
      - exit_status: "*"
```
have a value for `soft_fail` that is not compatible with the `soft_fail` field for `triggerStep` as [defined in the schema](https://github.com/buildkite/pipeline-schema/blob/2fbbfc199bd66c0ff64303a2d9c7072ad24f3ce3/schema.json#L1266), which only allows boolean-like atoms.

Perhaps it might be worth enabling CI gating on these tests passing?
FWIW I'm not sure whether it's the schema or the instance data that's at fault here.
