### ISSUE TITLE
fields -> default warning with array

### ISSUE THREAD

**Issue by tonynguyenit18** [buildkite/pipeline-schema#16]
When provide array string to fieldss default, vs code shows warning
E.g
```yml
  - block: "Deploy to QA"
    fields:
      - select: "Regions"
        key: "deploy-regions"
        hint: "Which regions should we deploy this to? :earth_asia:"
        multiple: true
        default: ["ap-southeast-2", "eu-west-1"]
        options:
          - label: "Sydney"
            value: "ap-southeast-2"
          - label: "Ireland"
            value: "eu-west-1"
```
Error
![image](https://user-images.githubusercontent.com/37351890/127756897-a7021810-5c0a-4e65-8a35-857bb35eba96.png)
