### ISSUE TITLE
`type` is not a valid property on the `build` configuration on a `trigger` step.

### ISSUE THREAD

**Issue by ojkelly** [buildkite/pipeline-schema#34]
https://github.com/buildkite/pipeline-schema/blob/9d1f70f8a8849a98f348dd91bc81964ad04eeddd/schema.json#L1115

**Comment by chaoyangnz** [comment]
same issue

**Comment by thejcannon** [comment]
Can you say more? The following pipeline is valid:

```yaml
steps:
    - trigger: foobar
       type: trigger
```
