### ISSUE TITLE
Block step is not allowed under steps > group > steps

### ISSUE THREAD

**Issue by tetienne** [buildkite/pipeline-schema#35]
With the following pipeline, 

```yaml
steps:
  - group: ":terraform: Staging Terraform"
    key: "staging-terraform"
    steps:
      - block: ":rocket: Release!"
        branches: $BUILDKITE_PIPELINE_DEFAULT_BRANCH
        key: wait-release-confirmation
        depends_on: start-gate

```
when checking with the current schema, I got the following error:

```
Schema validation errors were encountered.
  pipeline.yml::$.steps[0]: {'group': ':terraform: Staging Terraform', 'key': 'staging-terraform', 'steps': [{'block': ':rocket: Release!', 'branches': '$BUILDKITE_PIPELINE_DEFAULT_BRANCH', 'key': 'wait-release-confirmation', 'depends_on': 'start-gate'}]} is not valid under any of the given schemas
  Underlying errors caused this.
  Best Match:
    $.steps[0]: Additional properties are not allowed ('steps', 'group' were unexpected)
```

while Buildkite has no issue to read it.

This issue prevent us to apply the schema as pre-commit hook.
