### ISSUE TITLE
input step not supported in group

### ISSUE THREAD

**Issue by Techn1x** [buildkite/pipeline-schema#57]
buildkite yaml like this
```yaml
  - group: "Optional branch deploys"
    steps:
      - input: "Release to personal staging?"
        depends_on: "build-node-modules"
```

Produces an error in vscode `Property input is not allowed. yaml-schema: buildkite`

![image](https://github.com/buildkite/pipeline-schema/assets/1049837/c6620221-df5d-4007-bcc4-4a80ed2329f5)

Looks similar to this issue that was fixed https://github.com/buildkite/pipeline-schema/issues/8 - probably need to do someting similar for groups

I can confirm the code I gave above does indeed work.
