### ISSUE TITLE
Should we document fields `null`-ability?

### ISSUE THREAD

**Issue by thejcannon** [buildkite/pipeline-schema#93]
👋 

`#/definitions/waitStep/wait` having `{"type": "null"}` is a bit of an outlier (only one other instance, and its `#/definitions/dependsOn`).

I'm guessing it is documented because [wait step docs](https://buildkite.com/docs/pipelines/wait-step) explicitly call out `null` as a value you can use. However, from some light testing, BK is totally fine with other fields being `null` too!

```yaml
steps:
  - trigger: foo
     depends_on: ~
     key: ~
  - command: bar
     env: ~
     retry: ~
```

So, curious if, for correctness sake, most fields should be exploded into support `null`, or if for conciseness they shouldn't.
